spring:
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers:
            - localhost:9092
      bindings:
        input:
          destination: processor
        output:
          destination: sink

server:
  port: 8082
